---
- name: VSCode  ----  Snippets  ----  Copy code snippets to VSCode config in /home/{{ default_user }}
  ansible.builtin.copy:
    src: "../files/snippets"
    dest: "/home/{{ default_user }}/.config/Code/User"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: u=rw,g=r,o=
