---
- name: VSCode  ----  Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  block:

    - name: VSCode  ----  Ubuntu  ----  Install
      community.general.snap:
        name:
          - code
        state: present
        classic: true
      when: not is_test | default(false)

- name: VSCode  ----  Arch
  when: ansible_facts['os_family'] == "Archlinux"
  block:

    - name: VSCode  ----  Arch  ----  Install
      community.general.pacman:
        name:
          - code
        state: present
        update_cache: true

- name: VSCode  ----  Snippets
  ansible.builtin.import_tasks: 10-snippets.yml
