---
- name: ClamAV  ----  Scan  ----  Run scan
  ansible.builtin.shell: clamscan -r "{{ scan_path }}" --infected  --database="{{ clamav_database_dir }}"
  args:
    executable: /bin/bash
  register: clamscan_out
  failed_when: false
  become: true

- name: ClamAV  ----  Scan  ----  Show scan results (list only infected files)
  ansible.builtin.debug:
    msg: "{{ ['Return Code: ' ~ clamscan_out.rc] + clamscan_out.stdout.split('\n') + (['', 'STDERR:'] + clamscan_out.stderr.split('\n') if clamscan_out.stderr | length > 0 else []) }}"

- name: ClamAV  ----  Scan  ----  Assert scan completed successfully
  ansible.builtin.assert:
    that:
      - clamscan_out.rc == 0
    fail_msg: "{{ 'Found infected files' if clamscan_out.rc == 1 else 'Exit on hard error' }}"
    success_msg: "Scan completed successfully - no infected files found"
