---
- name: ClamAV  ----  Scan  ----  Run scan
  ansible.builtin.shell: clamscan -r "{{ scan_path }}" --infected  --database="{{ clamav_database_dir }}"
  args:
    executable: /bin/bash
  register: clamscan_out
  failed_when: false
  become: true

- name: ClamAV  ----  Scan  ----  Show scan results (list only infected files)
  ansible.builtin.debug:
    msg: "{{ ['Return Code: ' ~ clamscan_out.rc] + clamscan_out.stdout.split('\n') + (['', 'STDERR:'] + clamscan_out.stderr.split('\n') if clamscan_out.stderr | length > 0 else []) }}"
  failed_when: clamscan_out.rc > 0

- name: ClamAV  ----  Scan  ----  Fail on hard errors
  ansible.builtin.fail:
    msg: "ClamAV scan failed with return code {{ clamscan_out.rc }}"
  when: clamscan_out.rc >= 2
