---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  sync:assets-from-github:
    desc: 'Sync assets from the central sommerfeldio/.github repository'
    cmds:
      - echo "Syncing assets from the central sommerfeldio/.github repository..."
      - task: common:download
        vars: { DEST: ".github/copilot-instructions.md", URL: "{{ .REPO }}/refs/heads/main/.github/copilot-instructions.md" }
      - task: common:download
        vars: { DEST: ".vscode/settings.json", URL: "{{ .REPO }}/refs/heads/main/.vscode/settings.json" }
      - task: common:download
        vars: { DEST: ".github/workflows/codeql.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/codeql.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-issues.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-issues.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-labels.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-labels.yml" }

  # ===============================================================================================

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose down --remove-orphans
      - rm -rf .cache
      - rm -rf tests/.vagrant
      - rm -rf node_modules
      - rm -rf target
      - sudo rm -rf .ansible
      - find . -type f -exec chmod +r {} +
      - find . -type d -exec chmod +r {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for: ['yaml', 'filenames', 'folders', 'ansible'] # 'workflows', 'markdown-links',
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  test:
    desc: 'Run roles on all Vagrantboxes in sequence'
    summary: >
      Test roles on all supported operating systems using Vagrant. Reboot Vagrantboxes during test
      to ensure all kernel modules that are required for Docker are loaded. This task updates the
      Vagrantboxes to the latest version before running the tests.
    dir: tests
    cmds:
      - rm -rf .vagrant
      - vagrant box update
      - task: test:arch
      - task: test:ubuntu

  test:arch:
    desc: 'Run roles on Arch Linux Vagrantbox'
    summary: >
      Test Docker roles on Arch Linux using Vagrant. Reboot Vagrantbox during test to ensure all
      kernel modules that are required for Docker are loaded.
    dir: tests
    cmds:
      - task: internal:cleanup:vagrant
        vars: { BOX: 'arch' }
      - task: internal:test
        vars: { BOX: 'arch' }
      - task: internal:cleanup:vagrant
        vars: { BOX: 'arch' }

  test:ubuntu:
    desc: 'Run roles on Ubuntu Vagrantbox'
    summary: >
      Test Docker roles on Ubuntu using Vagrant. Reboot Vagrantbox during test to ensure all
      Ubuntu updates are installed.
    dir: tests
    cmds:
      - task: internal:cleanup:vagrant
        vars: { BOX: 'ubuntu' }
      - task: internal:test
        vars: { BOX: 'ubuntu' }
      - task: internal:cleanup:vagrant
        vars: { BOX: 'ubuntu' }

  internal:test:
    desc: 'Run roles on Vagrantbox'
    internal: true
    dir: tests
    cmds:
      - vagrant validate
      - time vagrant up {{ .BOX }}
      - vagrant halt {{ .BOX }}
      - vagrant up {{ .BOX }}
      # - vagrant ssh {{ .BOX }}
      # - docker run --rm -it chef/inspec:5.22.76 exec https://github.com/sommerfeld-io/inspec-profiles/tree/main/profiles/linux-essentials  --no-distinct-exit --chef-license=accept
      # TODO ... run inspec tests here

  internal:cleanup:vagrant:
    desc: 'Remove vagrantbox'
    internal: true
    dir: tests
    cmds:
      - vagrant halt {{ .BOX }}
      - vagrant destroy -f {{ .BOX }}
