---
version: '3.42.1'

dotenv: ['.env']

vars:
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  cleanup: .task/cleanup/taskfile.yml
  common: .task/common/taskfile.yml
  test:
    taskfile: tests/taskfile.yml
    dir: tests

tasks:

  compose:pull:
    desc: 'Pull all container images for linting and validation'
    cmds:
      - docker compose pull

  symlinks:
    desc: 'Create symlinks for shared files'
    cmds:
      - ln -sf "$(pwd)/.github/copilot-instructions.md" "$(pwd)/CLAUDE.md"

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - task: cleanup:filesystem
      - for: ['yaml', 'filenames', 'folders', 'ansible'] # 'workflows', 'markdown-links',
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}
      - task: test:lint
