# -*- mode: ruby -*-
# vi: set ft=ruby :


## Function to set basic configuration for a Vagrant box.
##
## @param box [Vagrant::VM] The Vagrant VM object
## @param box_name [String] The name of the Vagrant box (the underlying OS)
## @param hostname [String] The hostname to set for the VM
def basic_box_config(box, box_name, hostname)
  box.vm.provider "virtualbox" do |vb|
    vb.name = hostname

    vb.gui = false
    vb.cpus = 2
    vb.memory = 2048
  end

  box.vm.box = box_name
  box.vm.hostname = hostname
end


## Function to run the ansible provisioner (which is the same for all supported boxes)
## without repeating the code for each box.
##
## @param box [Vagrant::VM] The Vagrant VM object
## @param box_name [String] The name of the Vagrant box (the underlying OS)
def run_ansible_provisioner(box, box_name)
  box.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible-playbook.yml"
    # ansible.verbose = "vvv"
    ansible.groups = {
      "system_under_test" => [box_name]
    }
    ansible.host_vars = {
      box_name => {
        "ansible_user" => "vagrant",
        # "ansible_python_interpreter" => "/usr/bin/python",
      }
    }
    ansible.extra_vars = {
      "ps1" => '${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $ ',
      "architecture" => "amd64",
      "github" => "git@github.com",
      "dir_work" => "/home/{{ ansible_user }}/work",
      "dir_repos" => "{{ dir_work }}/repos",
      "dir_repos_sommerfeld_io" => "{{ dir_repos }}/sommerfeld-io",
      "dir_repos_sommerfeld_io_archive" => "{{ dir_repos }}/sommerfeld-io-archive",
      "dir_repos_sebastian_sommerfeld_io" => "{{ dir_repos }}/sebastian-sommerfeld-io",
      "docker_stacks_dir" => "/home/{{ ansible_user }}/.docker-stacks",
    }
  end
end


## Vagrant configuration to define boxes for different operating systems. Both Arch
## Linux and Ubuntu are supported.
##
## Both boxes are updated to the latest version before running the ansible provisioner.
## For Arch this is a full system upgrade, for Ubuntu this means multiple release upgrades.
Vagrant.configure("2") do |config|

  ## Arch Linux
  config.vm.define "arch" do |arch|
    ARCH_BOX_NAME = "generic/arch"
    ARCH_HOSTNAME = "ansible-roles-test-arch"

    basic_box_config(arch, ARCH_BOX_NAME, ARCH_HOSTNAME)

    arch.vm.provision "shell", inline: <<-SHELL
      pacman -Sy archlinux-keyring --noconfirm
      pacman -Syu --noconfirm # Update system and package database
      pacman -S python --noconfirm

      echo "----------------------------------------------------"
      hostnamectl
      echo "----------------------------------------------------"
    SHELL

    run_ansible_provisioner(arch, ARCH_HOSTNAME)
  end

  ## Ubuntu
  config.vm.define "ubuntu" do |ubuntu|
    UBUNTU_BOX_NAME = "ubuntu/jammy64" # 22.04 LTS
    UBUNTU_HOSTNAME = "ansible-roles-test-ubuntu"

    ## When you run `do-release-upgrade` from 22.04 (LTS), it first upgrades to the next LTS
    ## release (24.04), skipping no longer supported releases. Subsequent `do-release-upgrade`
    ## commands will upgrade through available releases.
    # UBUNTU_VERSIONS = ["24.04", "25.04", "25.10"]
    UBUNTU_VERSIONS = ["24.04", "25.04"]
    ## CAUTION: This seems to be an unstable approach to updating ububtu because as of 26.04
    ## the 25.xx releases should no longer be supported. So this code may break in the future.
    ## List of releases:https://documentation.ubuntu.com/project/release-team/list-of-releases

    basic_box_config(ubuntu, UBUNTU_BOX_NAME, UBUNTU_HOSTNAME)

    ubuntu.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive

      apt-get update
      apt-get upgrade -y
      apt-get dist-upgrade -y
      apt-get autoremove -y
      apt-get autoclean

      apt-get install -y update-manager-core
      sed -i 's/Prompt=lts/Prompt=normal/' /etc/update-manager/release-upgrades # Allow non-LTS upgrades
    SHELL

    UBUNTU_VERSIONS.each do |version|
      ubuntu.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive

        echo "---------- upgrading to Ubuntu #{version} ----------"

        rm -f /var/run/reboot-required*
        do-release-upgrade -f DistUpgradeViewNonInteractive

        echo "----------------------------------------------------"
        hostnamectl
        echo "----------------------------------------------------"
      SHELL
    end

    run_ansible_provisioner(ubuntu, UBUNTU_HOSTNAME)
  end
end
