---
- name: Filesystem  ----  Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: u=rwx,g=rx,o=
  with_items:
    - "/home/{{ default_user }}/.config"
    - "/home/{{ default_user }}/.config/autostart"
    - "{{ dir_work }}"
    - "{{ dir_repos }}"
    - "{{ dir_repos_bad_android }}"
    - "{{ dir_repos_sommerfeld_io }}"
    - "{{ dir_repos_sommerfeld_io_archive }}"
    - "{{ dir_repos_sebastian_sommerfeld_io }}"
    - "/home/{{ default_user }}/tmp"
