---
- name: Task  ----  Configure  ----  Ensure TASK_X_REMOTE_TASKFILES is absent from .bashrc
  ansible.builtin.lineinfile:
    dest: "/home/{{ default_user }}/.bashrc"
    state: absent
    regexp: '^export TASK_X_REMOTE_TASKFILES='
